export const GET_LEADS="GET_LEADS";
export const DELETE_LEADS="DELETE_LEADS";
export const ADD_LEADS="ADD_LEADS";
export const GET_ERRORS="GET_ERRORS";
export const GET_MESSAGES="GET_MESSAGES";
export  const CREATE_MESSAGES="CREATE_MESSAGES"